format = "$all"

[directory]
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[git_status]
untracked = "?$count"
stashed = "\\$$count"
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "✘$count"

[battery]
format = "[$symbol $percentage]($style) "

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[[battery.display]]  # "bold yellow" style when capacity is between 30% and 1000%
threshold = 100
style = "blue"
